# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.cache/wt [current_project]
set_property parent.project_path /home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {/home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.srcs/sources_1/imports/Important SRC Files/Generic_counter.v}
  {/home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.srcs/sources_1/imports/Important SRC Files/Multiplexer.v}
  /home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.srcs/sources_1/imports/sources_1/new/Frame_gen.v
  {/home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.srcs/sources_1/imports/Important SRC Files/VGA_Display2.v}
  {/home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.srcs/sources_1/imports/Important SRC Files/Seg7.v}
  {/home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.srcs/sources_1/imports/Important SRC Files/Clock_Control.v}
  /home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.srcs/sources_1/new/LEDs_speed.v
  /home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.srcs/sources_1/new/Q1_Wrapper.v
  /home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.srcs/sources_1/imports/sources_1/imports/new/VGA_Wrapper2.v
  /home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.srcs/sources_1/new/Top_Wrapper.v
}
read_xdc /home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.srcs/constrs_1/new/XDCFile.xdc
set_property used_in_implementation false [get_files /home/s2475012/Desktop/Digital-Lab-W7Exam/Digital-Lab-W7Exam.srcs/constrs_1/new/XDCFile.xdc]

synth_design -top Top_Wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef Top_Wrapper.dcp
catch { report_utilization -file Top_Wrapper_utilization_synth.rpt -pb Top_Wrapper_utilization_synth.pb }
