# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.cache/wt [current_project]
set_property parent.project_path /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/SRCs/Generic_counter.v
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/SRCs/VGA_Interface.v
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/SRCs/Frame_Generator.v
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/SRCs/Seg7Control.v
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/SRCs/Multiplexer_attempt.v
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/SRCs/VGA_Program.v
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/SRCs/Target_Generator.v
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/SRCs/Snake_Control.v
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/SRCs/Navigation_State_Machine.v
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/SRCs/MSM.v
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/SRCs/Score_Counter.v
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/new/7Seg_Wrapper.v
  /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/sources_1/imports/SRCs/Input-Output.v
}
read_xdc /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/constrs_1/imports/Constraints/Snake_GameXDC.xdc
set_property used_in_implementation false [get_files /home/s2475012/Desktop/Snake_Game_2015V/Snake_Game_2015V.srcs/constrs_1/imports/Constraints/Snake_GameXDC.xdc]

synth_design -top Input_Output -part xc7a35tcpg236-1
write_checkpoint -noxdef Input_Output.dcp
catch { report_utilization -file Input_Output_utilization_synth.rpt -pb Input_Output_utilization_synth.pb }
