# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s2475012/Desktop/Hello_lots_of_worlds/Hello_lots_of_worlds.cache/wt [current_project]
set_property parent.project_path /home/s2475012/Desktop/Hello_lots_of_worlds/Hello_lots_of_worlds.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /home/s2475012/Desktop/Hello_lots_of_worlds/Hello_lots_of_worlds.srcs/sources_1/new/Hello_lots_of_worlds.v
read_xdc /home/s2475012/Desktop/Hello_lots_of_worlds/Hello_lots_of_worlds.srcs/constrs_1/new/Hello_lots_of_worldsXDC.xdc
set_property used_in_implementation false [get_files /home/s2475012/Desktop/Hello_lots_of_worlds/Hello_lots_of_worlds.srcs/constrs_1/new/Hello_lots_of_worldsXDC.xdc]

synth_design -top Hello_lots_of_worlds -part xc7a35tcpg236-1
write_checkpoint -noxdef Hello_lots_of_worlds.dcp
catch { report_utilization -file Hello_lots_of_worlds_utilization_synth.rpt -pb Hello_lots_of_worlds_utilization_synth.pb }
