# Horizontal and Vertical Sync
set_property PACKAGE_PIN P19 [get_ports HS]
    set_property IOSTANDARD LVCMOS33 [get_ports HS]
set_property PACKAGE_PIN R19 [get_ports VS]
    set_property IOSTANDARD LVCMOS33 [get_ports VS]
set_property PACKAGE_PIN R2 [get_ports Reset]
    set_property IOSTANDARD LVCMOS33 [get_ports Reset]

# Clk
set_property PACKAGE_PIN W5 [get_ports Clk]
    set_property IOSTANDARD LVCMOS33 [get_ports Clk]
    
# Fun Controls:
set_property PACKAGE_PIN T17 [get_ports {CNTRL[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CNTRL[0]}]
set_property PACKAGE_PIN W19 [get_ports {CNTRL[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CNTRL[1]}]
set_property PACKAGE_PIN U17 [get_ports {CNTRL[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CNTRL[2]}]
set_property PACKAGE_PIN T18 [get_ports {CNTRL[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {CNTRL[3]}]

# Slide Switch In
set_property PACKAGE_PIN V17 [get_ports {Colour_In[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_In[0]}]
set_property PACKAGE_PIN V16 [get_ports {Colour_In[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_In[1]}]
set_property PACKAGE_PIN W16 [get_ports {Colour_In[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_In[2]}]
set_property PACKAGE_PIN W17 [get_ports {Colour_In[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_In[3]}]
set_property PACKAGE_PIN W15 [get_ports {Colour_In[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_In[4]}]
set_property PACKAGE_PIN V15 [get_ports {Colour_In[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_In[5]}]
set_property PACKAGE_PIN W14 [get_ports {Colour_In[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_In[6]}]
set_property PACKAGE_PIN W13 [get_ports {Colour_In[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_In[7]}]
set_property PACKAGE_PIN V2 [get_ports {Colour_In[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_In[8]}]
set_property PACKAGE_PIN T3 [get_ports {Colour_In[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_In[9]}]
set_property PACKAGE_PIN T2 [get_ports {Colour_In[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_In[10]}]
set_property PACKAGE_PIN R3 [get_ports {Colour_In[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_In[11]}]

#VGA Ports Out
set_property PACKAGE_PIN G19 [get_ports {Colour_Out[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[0]}]
set_property PACKAGE_PIN H19 [get_ports {Colour_Out[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[1]}]
set_property PACKAGE_PIN J19 [get_ports {Colour_Out[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[2]}]
set_property PACKAGE_PIN N19 [get_ports {Colour_Out[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[3]}]
set_property PACKAGE_PIN J17 [get_ports {Colour_Out[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[4]}]
set_property PACKAGE_PIN H17 [get_ports {Colour_Out[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[5]}]
set_property PACKAGE_PIN G17 [get_ports {Colour_Out[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[6]}]
set_property PACKAGE_PIN D17 [get_ports {Colour_Out[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[7]}]
set_property PACKAGE_PIN N18 [get_ports {Colour_Out[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[8]}]
set_property PACKAGE_PIN L18 [get_ports {Colour_Out[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[9]}]
set_property PACKAGE_PIN K18 [get_ports {Colour_Out[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[10]}]
set_property PACKAGE_PIN J18 [get_ports {Colour_Out[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[11]}]