# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s2475012/Desktop/7-World-of-State-Machines/7-World-of-State-Machines.cache/wt [current_project]
set_property parent.project_path /home/s2475012/Desktop/7-World-of-State-Machines/7-World-of-State-Machines.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {/home/s2475012/Desktop/7-World-of-State-Machines/7-World-of-State-Machines.srcs/sources_1/imports/Important SRC Files/Seg7.v}
  /home/s2475012/Desktop/7-World-of-State-Machines/7-World-of-State-Machines.srcs/sources_1/new/Sync_Mach.v
}
read_xdc /home/s2475012/Desktop/7-World-of-State-Machines/7-World-of-State-Machines.srcs/constrs_1/new/Sync_MachXDC.xdc
set_property used_in_implementation false [get_files /home/s2475012/Desktop/7-World-of-State-Machines/7-World-of-State-Machines.srcs/constrs_1/new/Sync_MachXDC.xdc]

synth_design -top Sync_Mach -part xc7a35tcpg236-1
write_checkpoint -noxdef Sync_Mach.dcp
catch { report_utilization -file Sync_Mach_utilization_synth.rpt -pb Sync_Mach_utilization_synth.pb }
