set_property PACKAGE_PIN W5 [get_ports Clk]
    set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property PACKAGE_PIN T17 [get_ports Reset]
    set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property PACKAGE_PIN V17 [get_ports Enable]
    set_property IOSTANDARD LVCMOS33 [get_ports Enable]

set_property PACKAGE_PIN U16 [get_ports LED]
    set_property IOSTANDARD LVCMOS33 [get_ports LED]

set_property PACKAGE_PIN U2 [get_ports {Seg_Select[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Select[0]}]
set_property PACKAGE_PIN U4 [get_ports {Seg_Select[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Select[1]}]
set_property PACKAGE_PIN V4 [get_ports {Seg_Select[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Select[2]}]
set_property PACKAGE_PIN W4 [get_ports {Seg_Select[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Select[3]}]

set_property PACKAGE_PIN W7 [get_ports {Dec_Out[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[0]}]
set_property PACKAGE_PIN W6 [get_ports {Dec_Out[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[1]}]
set_property PACKAGE_PIN U8 [get_ports {Dec_Out[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[2]}]
set_property PACKAGE_PIN V8 [get_ports {Dec_Out[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[3]}]
set_property PACKAGE_PIN U5 [get_ports {Dec_Out[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[4]}]
set_property PACKAGE_PIN V5 [get_ports {Dec_Out[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[5]}]
set_property PACKAGE_PIN U7 [get_ports {Dec_Out[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[6]}]
set_property PACKAGE_PIN V7 [get_ports {Dec_Out[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[7]}]
