#Clock Input
set_property PACKAGE_PIN W5 [get_ports Clk]
    set_property IOSTANDARD LVCMOS33 [get_ports Clk]

#All Buttons
set_property PACKAGE_PIN U18 [get_ports Reset]
    set_property IOSTANDARD LVCMOS33 [get_ports Reset]  
set_property PACKAGE_PIN W19 [get_ports BTNL]
    set_property IOSTANDARD LVCMOS33 [get_ports BTNL]
set_property PACKAGE_PIN T17 [get_ports BTNR]
    set_property IOSTANDARD LVCMOS33 [get_ports BTNR]
set_property PACKAGE_PIN T18 [get_ports BTNU]
    set_property IOSTANDARD LVCMOS33 [get_ports BTNU]
set_property PACKAGE_PIN U17 [get_ports BTND]
    set_property IOSTANDARD LVCMOS33 [get_ports BTND]
#Speed Control
set_property PACKAGE_PIN R2 [get_ports Game_Speed]
        set_property IOSTANDARD LVCMOS33 [get_ports Game_Speed]
        
#Select 7-Segment Display
set_property PACKAGE_PIN U2 [get_ports {Seg_Select[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Select[0]}]
set_property PACKAGE_PIN U4 [get_ports {Seg_Select[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Select[1]}]
set_property PACKAGE_PIN V4 [get_ports {Seg_Select[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Select[2]}]
set_property PACKAGE_PIN W4 [get_ports {Seg_Select[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Select[3]}]

#Display Number on 7-Segment Display
set_property PACKAGE_PIN W7 [get_ports {Hex_Out[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Hex_Out[0]}]
set_property PACKAGE_PIN W6 [get_ports {Hex_Out[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Hex_Out[1]}]
set_property PACKAGE_PIN U8 [get_ports {Hex_Out[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Hex_Out[2]}]
set_property PACKAGE_PIN V8 [get_ports {Hex_Out[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Hex_Out[3]}]
set_property PACKAGE_PIN U5 [get_ports {Hex_Out[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Hex_Out[4]}]
set_property PACKAGE_PIN V5 [get_ports {Hex_Out[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Hex_Out[5]}]
set_property PACKAGE_PIN U7 [get_ports {Hex_Out[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Hex_Out[6]}]
set_property PACKAGE_PIN V7 [get_ports {Hex_Out[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Hex_Out[7]}]

#Colour Out Controls
set_property PACKAGE_PIN  G19 [get_ports {Colour_Out[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[0]}]
set_property PACKAGE_PIN  H19 [get_ports {Colour_Out[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[1]}]
set_property PACKAGE_PIN  J19 [get_ports {Colour_Out[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[2]}]
set_property PACKAGE_PIN  N19 [get_ports {Colour_Out[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[3]}]
set_property PACKAGE_PIN  J17 [get_ports {Colour_Out[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[4]}]
set_property PACKAGE_PIN  H17 [get_ports {Colour_Out[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[5]}]
set_property PACKAGE_PIN  G17 [get_ports {Colour_Out[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[6]}]
set_property PACKAGE_PIN  D17 [get_ports {Colour_Out[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[7]}]
set_property PACKAGE_PIN  N18 [get_ports {Colour_Out[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[8]}]
set_property PACKAGE_PIN  L18 [get_ports {Colour_Out[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[9]}]
set_property PACKAGE_PIN  K18 [get_ports {Colour_Out[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[10]}]
set_property PACKAGE_PIN  J18 [get_ports {Colour_Out[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[11]}]

#HS and VS
set_property PACKAGE_PIN P19 [get_ports HS]
    set_property IOSTANDARD LVCMOS33 [get_ports HS]
set_property PACKAGE_PIN R19 [get_ports VS]
    set_property IOSTANDARD LVCMOS33 [get_ports VS]