# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s2475012/Desktop/Timing-Worlds/Timing-Worlds.cache/wt [current_project]
set_property parent.project_path /home/s2475012/Desktop/Timing-Worlds/Timing-Worlds.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /home/s2475012/Desktop/Timing-Worlds/Timing-Worlds.srcs/sources_1/imports/new/Counting_worlds.v
read_xdc /home/s2475012/Desktop/Timing-Worlds/Timing-Worlds.srcs/constrs_1/imports/new/Timing_the_worldXDC.xdc
set_property used_in_implementation false [get_files /home/s2475012/Desktop/Timing-Worlds/Timing-Worlds.srcs/constrs_1/imports/new/Timing_the_worldXDC.xdc]

synth_design -top Counting_worlds -part xc7a35tcpg236-1
write_checkpoint -noxdef Counting_worlds.dcp
catch { report_utilization -file Counting_worlds_utilization_synth.rpt -pb Counting_worlds_utilization_synth.pb }
