# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s2475012/Desktop/5-Colour-World/Week5.2.1.cache/wt [current_project]
set_property parent.project_path /home/s2475012/Desktop/5-Colour-World/Week5.2.1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/s2475012/Desktop/5-Colour-World/Week5.2.1.srcs/sources_1/new/Frame_gen.v
  /home/s2475012/Desktop/5-Colour-World/Week5.2.1.srcs/sources_1/imports/new/VGA_Display2.v
  /home/s2475012/Desktop/5-Colour-World/Week5.2.1.srcs/sources_1/imports/new/Clock_Control.v
  /home/s2475012/Desktop/5-Colour-World/Week5.2.1.srcs/sources_1/imports/new/VGA_Wrapper2.v
}
read_xdc /home/s2475012/Desktop/5-Colour-World/Week5.2.1.srcs/constrs_1/imports/new/VGAXDC.xdc
set_property used_in_implementation false [get_files /home/s2475012/Desktop/5-Colour-World/Week5.2.1.srcs/constrs_1/imports/new/VGAXDC.xdc]

synth_design -top VGA_Wrapper2 -part xc7a35tcpg236-1
write_checkpoint -noxdef VGA_Wrapper2.dcp
catch { report_utilization -file VGA_Wrapper2_utilization_synth.rpt -pb VGA_Wrapper2_utilization_synth.pb }
