# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s2475012/Desktop/ShiftRegister/ShiftRegister.cache/wt [current_project]
set_property parent.project_path /home/s2475012/Desktop/ShiftRegister/ShiftRegister.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/s2475012/Desktop/ShiftRegister/ShiftRegister.srcs/sources_1/imports/new/Hello_synchronous_world.v
  /home/s2475012/Desktop/ShiftRegister/ShiftRegister.srcs/sources_1/imports/new/Shift_register.v
}
read_xdc /home/s2475012/Desktop/ShiftRegister/ShiftRegister.srcs/constrs_1/new/Shift_RegXDC.xdc
set_property used_in_implementation false [get_files /home/s2475012/Desktop/ShiftRegister/ShiftRegister.srcs/constrs_1/new/Shift_RegXDC.xdc]

synth_design -top Shift_register -part xc7a35tcpg236-1
write_checkpoint -noxdef Shift_register.dcp
catch { report_utilization -file Shift_register_utilization_synth.rpt -pb Shift_register_utilization_synth.pb }
