# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/s2475012/Desktop/5-Timing-World-Decimal/Week 5.1.cache/wt} [current_project]
set_property parent.project_path {/home/s2475012/Desktop/5-Timing-World-Decimal/Week 5.1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {/home/s2475012/Desktop/5-Timing-World-Decimal/Week 5.1.srcs/sources_1/new/Seg7.v}
  {/home/s2475012/Desktop/5-Timing-World-Decimal/Week 5.1.srcs/sources_1/imports/new/Multiplexer_attempt.v}
  {/home/s2475012/Desktop/5-Timing-World-Decimal/Week 5.1.srcs/sources_1/imports/new/Generic_counter.v}
  {/home/s2475012/Desktop/5-Timing-World-Decimal/Week 5.1.srcs/sources_1/imports/new/Generic_wrapper.v}
}
read_xdc {{/home/s2475012/Desktop/5-Timing-World-Decimal/Week 5.1.srcs/constrs_1/imports/new/GenericXDC.xdc}}
set_property used_in_implementation false [get_files {{/home/s2475012/Desktop/5-Timing-World-Decimal/Week 5.1.srcs/constrs_1/imports/new/GenericXDC.xdc}}]

synth_design -top Generic_wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef Generic_wrapper.dcp
catch { report_utilization -file Generic_wrapper_utilization_synth.rpt -pb Generic_wrapper_utilization_synth.pb }
