#Bit Controls
set_property PACKAGE_PIN V17 [get_ports {Controls[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Controls[0]}]
set_property PACKAGE_PIN V16 [get_ports {Controls[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Controls[1]}]
set_property PACKAGE_PIN W16 [get_ports {Controls[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Controls[2]}]
set_property PACKAGE_PIN W17 [get_ports {Controls[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Controls[3]}]

#Other Controls
set_property PACKAGE_PIN V15 [get_ports DOT]
    set_property IOSTANDARD LVCMOS33 [get_ports DOT]
set_property PACKAGE_PIN W13 [get_ports {Seg_In[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_In[0]}]
set_property PACKAGE_PIN V2 [get_ports {Seg_In[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_In[1]}]

#LED Controls
set_property PACKAGE_PIN U16 [get_ports {LEDs[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN E19 [get_ports {LEDs[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U19 [get_ports {LEDs[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN V19 [get_ports {LEDs[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN U15 [get_ports {LEDs[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN V14 [get_ports {LEDs[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[5]}]
set_property PACKAGE_PIN V13 [get_ports {LEDs[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[6]}]

#7-Segment Display Anode
set_property PACKAGE_PIN U2 [get_ports {Display[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Display[0]}]
set_property PACKAGE_PIN U4 [get_ports {Display[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Display[1]}]
set_property PACKAGE_PIN V4 [get_ports {Display[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Display[2]}]
set_property PACKAGE_PIN W4 [get_ports {Display[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Display[3]}]

#7-Segment Display Cathode
set_property PACKAGE_PIN W7 [get_ports {Display[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Display[4]}]
set_property PACKAGE_PIN W6 [get_ports {Display[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Display[5]}]
set_property PACKAGE_PIN U8 [get_ports {Display[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Display[6]}]
set_property PACKAGE_PIN V8 [get_ports {Display[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Display[7]}]
set_property PACKAGE_PIN U5 [get_ports {Display[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Display[8]}]
set_property PACKAGE_PIN V5 [get_ports {Display[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Display[9]}]
set_property PACKAGE_PIN U7 [get_ports {Display[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Display[10]}]
set_property PACKAGE_PIN V7 [get_ports {Display[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Display[11]}]

#set_property PACKAGE_PIN V17 [get_ports Count_Enable]
#    set_property IOSTANDARD LVCMOS33 [get_ports Count_Enable]
#set_property PACKAGE_PIN V16 [get_ports Count_Control]
#    set_property IOSTANDARD LVCMOS33 [get_ports Count_Control]
#set_property PACKAGE_PIN T17 [get_ports Reset]
#    set_property IOSTANDARD LVCMOS33 [get_ports Reset]

#set_property PACKAGE_PIN U16 [get_ports {LEDs[0]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]
#set_property PACKAGE_PIN E19 [get_ports {LEDs[1]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
#set_property PACKAGE_PIN U19 [get_ports {LEDs[2]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
#set_property PACKAGE_PIN V19 [get_ports {LEDs[3]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
#set_property PACKAGE_PIN W18 [get_ports {LEDs[4]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[4]}]
#set_property PACKAGE_PIN U15 [get_ports {LEDs[5]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[5]}]
#set_property PACKAGE_PIN U14 [get_ports {LEDs[6]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[6]}]
#set_property PACKAGE_PIN V14 [get_ports {LEDs[7]}]
#    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[7]}]

#set_property PACKAGE_PIN W5 [get_ports CLK]
#    set_property IOSTANDARD LVCMOS33 [get_ports CLK]