# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/s2475012/Desktop/4-Decoding-the-World/project_1.cache/wt [current_project]
set_property parent.project_path /home/s2475012/Desktop/4-Decoding-the-World/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/s2475012/Desktop/4-Decoding-the-World/project_1.srcs/sources_1/imports/new/Decoding_the_world2.v
  /home/s2475012/Desktop/4-Decoding-the-World/project_1.srcs/sources_1/imports/new/Decoding_world_wrapper.v
}
read_xdc /home/s2475012/Desktop/4-Decoding-the-World/project_1.srcs/constrs_1/imports/new/Decoding_the_worldXDC.xdc
set_property used_in_implementation false [get_files /home/s2475012/Desktop/4-Decoding-the-World/project_1.srcs/constrs_1/imports/new/Decoding_the_worldXDC.xdc]

synth_design -top Decoding_world_wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef Decoding_world_wrapper.dcp
catch { report_utilization -file Decoding_world_wrapper_utilization_synth.rpt -pb Decoding_world_wrapper_utilization_synth.pb }
