set_property PACKAGE_PIN V17 [get_ports Count_Enable]
    set_property IOSTANDARD LVCMOS33 [get_ports Count_Enable]
set_property PACKAGE_PIN V16 [get_ports Count_Control]
    set_property IOSTANDARD LVCMOS33 [get_ports Count_Control]
set_property PACKAGE_PIN T17 [get_ports Reset]
    set_property IOSTANDARD LVCMOS33 [get_ports Reset]

set_property PACKAGE_PIN U16 [get_ports {LEDs[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN E19 [get_ports {LEDs[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U19 [get_ports {LEDs[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN V19 [get_ports {LEDs[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN W18 [get_ports {LEDs[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN U15 [get_ports {LEDs[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[5]}]
set_property PACKAGE_PIN U14 [get_ports {LEDs[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[6]}]
set_property PACKAGE_PIN V14 [get_ports {LEDs[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[7]}]

set_property PACKAGE_PIN W5 [get_ports CLK]
    set_property IOSTANDARD LVCMOS33 [get_ports CLK]