#Inputs
# Q1
set_property PACKAGE_PIN W5 [get_ports CLK]
    set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN U18 [get_ports Reset]
    set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property PACKAGE_PIN R2 [get_ports Enable]
    set_property IOSTANDARD LVCMOS33 [get_ports Enable]
#Q2.
set_property PACKAGE_PIN T18 [get_ports Increase]
    set_property IOSTANDARD LVCMOS33 [get_ports Increase]
set_property PACKAGE_PIN U17 [get_ports Decrease]
    set_property IOSTANDARD LVCMOS33 [get_ports Decrease]

# Horizontal and Vertical Sync
set_property PACKAGE_PIN P19 [get_ports HS]
    set_property IOSTANDARD LVCMOS33 [get_ports HS]
set_property PACKAGE_PIN R19 [get_ports VS]
    set_property IOSTANDARD LVCMOS33 [get_ports VS]

#Outputs
#Q1. Anodes
set_property PACKAGE_PIN U2 [get_ports {Seg_Select[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Select[0]}]
set_property PACKAGE_PIN U4 [get_ports {Seg_Select[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Select[1]}]
set_property PACKAGE_PIN V4 [get_ports {Seg_Select[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Select[2]}]
set_property PACKAGE_PIN W4 [get_ports {Seg_Select[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Seg_Select[3]}]
#Q1. Cathodes
set_property PACKAGE_PIN W7 [get_ports {Dec_Out[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[0]}]
set_property PACKAGE_PIN W6 [get_ports {Dec_Out[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[1]}]
set_property PACKAGE_PIN U8 [get_ports {Dec_Out[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[2]}]
set_property PACKAGE_PIN V8 [get_ports {Dec_Out[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[3]}]
set_property PACKAGE_PIN U5 [get_ports {Dec_Out[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[4]}]
set_property PACKAGE_PIN V5 [get_ports {Dec_Out[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[5]}]
set_property PACKAGE_PIN U7 [get_ports {Dec_Out[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[6]}]
set_property PACKAGE_PIN V7 [get_ports {Dec_Out[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Dec_Out[7]}]
#Q2.
set_property PACKAGE_PIN U16 [get_ports {LEDs[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN E19 [get_ports {LEDs[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN U19 [get_ports {LEDs[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN V19 [get_ports {LEDs[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]

#VGA Ports Out
set_property PACKAGE_PIN G19 [get_ports {Colour_Out[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[0]}]
set_property PACKAGE_PIN H19 [get_ports {Colour_Out[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[1]}]
set_property PACKAGE_PIN J19 [get_ports {Colour_Out[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[2]}]
set_property PACKAGE_PIN N19 [get_ports {Colour_Out[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[3]}]
set_property PACKAGE_PIN J17 [get_ports {Colour_Out[4]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[4]}]
set_property PACKAGE_PIN H17 [get_ports {Colour_Out[5]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[5]}]
set_property PACKAGE_PIN G17 [get_ports {Colour_Out[6]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[6]}]
set_property PACKAGE_PIN D17 [get_ports {Colour_Out[7]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[7]}]
set_property PACKAGE_PIN N18 [get_ports {Colour_Out[8]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[8]}]
set_property PACKAGE_PIN L18 [get_ports {Colour_Out[9]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[9]}]
set_property PACKAGE_PIN K18 [get_ports {Colour_Out[10]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[10]}]
set_property PACKAGE_PIN J18 [get_ports {Colour_Out[11]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {Colour_Out[11]}]